print.ICBOOT3 <-
function(x,...)
{
cat("Results")
cat("\nBootstrap SE ")
cat("\nCI for ")
cat("\nThreshold 1 ")
cat("\n  Lower Limit: ", x$LOWNORM1)
cat("\n  Upper Limit: ", x$UPNORM1)
cat("\n\nThreshold 2")
cat("\n  Lower Limit: ", x$LOWNORM2)
cat("\n  Upper Limit: ", x$UPNORM2)
cat("\n")
cat("\nPercentile ")
cat("\nCI for ")
cat("\nThreshold 1 ")
cat("\n  Lower Limit: ", x$LOWPERC1)
cat("\n  Upper Limit: ", x$UPPERC1)
cat("\n\nThreshold 2")
cat("\n  Lower Limit: ", x$LOWPERC2)
cat("\n  Upper Limit: ", x$UPPERC2)
cat("\n")
cat("\nParameters used")
cat("\n  Prevalences:", x$PREV)
cat("\n  Costs")
cat("\n    C11,C21,C31:", x$COSTS[1:3])
cat("\n    C12,C22,C32:", x$COSTS[4:6])
cat("\n    C13,C23,C33:", x$COSTS[7:9])
cat("\n")
}
